from PageLocators.process_front_locator import ProcessPageLocator as PPL
from Common.basepage import BasePage
from time import sleep
class ProPage(BasePage):

    def list_pro_perc(self):
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(2)
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        text_1 = self.get_element_text(PPL.show_process_percent,doc="获取'显示进度占比'元素")
        return text_1

    def check_proc_percen(self):
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(2)
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        sleep(4)
        self.click_by_js(PPL.show_process_box,doc="勾选'显示进度占比'框")
        sleep(4)
        text_1 = self.get_list_length(PPL.list_process_percent,doc="获取进度占比元素个数")
        self.click_by_js(PPL.show_process_box,doc="取选'显示进度占比'框")
        sleep(4)
        text_2 = self.is_element_exsits(PPL.list_process_percent_1,doc="判断元素是否存在")
        return text_1,text_2

    def plumbing_finish_and_ignore(self):
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(2)
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        sleep(2)
        self.click_by_js(PPL.show_process_box,doc="勾选'显示进度占比'框")
        self.click(PPL.plumbing_finish,doc="水暖专业点'完成'")
        text_0 = self.get_element_text(PPL.plumbing_box_info,doc="获取弹框提示语")
        self.click_by_js(PPL.plumbing_sure,doc="水暖专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do,doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_finish_percent,doc="获取水暖专业完成进度")
        text_3 = self.get_element_text(PPL.money_result_finish_pro,doc="获取新能源-收资-成果完成进度")
        text_4 = self.get_element_text(PPL.energy_money_finsh_pro,doc="获取新能源-收资-阶段完成进度")
        text_5 = self.get_element_text(PPL.energy_finsh_pro,doc="获取新能源-业务模块完成进度")
        text_6 = self.get_element_text(PPL.project_proc_new,doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(1)
        text_7 = self.get_element_text(PPL.process_percent,doc="获取列表页进度百分比")
        return text_0,text_1,text_2,text_3,text_4,text_5,text_6,text_7

    def communication_ignore(self):
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box,doc="勾选'显示进度占比'框")
        self.click(PPL.communication_ignore,doc="忽略'通信'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info,doc="获取弹框提示语")
        self.click_by_js(PPL.plumbing_sure,doc="水暖专业忽略弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.communication_do,doc="获取通信专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_finish_percent,doc="获取水暖专业完成进度")
        text_3 = self.get_element_text(PPL.plumbing_process_percent,doc="获取水暖专业进度占比")
        text_4 = self.get_element_text(PPL.money_result_finish_pro,doc="获取新能源-收资-成果完成进度")
        text_5 = self.get_element_text(PPL.energy_money_finsh_pro,doc="获取新能源-收资-阶段完成进度")
        text_6 = self.get_element_text(PPL.energy_finsh_pro,doc="获取新能源-业务模块完成进度")
        text_7 = self.get_element_text(PPL.project_proc_new,doc="项目状态完成进度")
        text_8 = self.get_element_text(PPL.communication_process_percent,doc="获取通信专业专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.communication_finish_percent,doc="获取通信专业专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.aerial_survey_process_percent,doc="获取航空测量专业进度'进度占比'")
        text_11 = self.get_element_text(PPL.resources_process_percent,doc="获取资源专业进度'进度占比'")
        text_12 = self.get_element_text(PPL.general_layout_process_percent,doc="获取总图专业进度'进度占比'")
        text_13 = self.get_element_text(PPL.ground_process_percent,doc="获取场区电气一次专业进度'进度占比'")
        text_14 = self.get_element_text(PPL.ground_two_process_percent,doc="获取场区电气二次专业进度'进度占比'")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(1)
        text_15 = self.get_element_text(PPL.process_percent,doc="获取列表页进度百分比")
        return text_0,text_1,text_2,text_3,text_4,text_5,text_6,text_7,text_8,text_9,text_10,text_11,text_12,text_13,text_14,text_15

    def aerial_survey_ignore(self):
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box,doc="勾选'显示进度占比'框")
        self.click(PPL.aerial_survey_ignore,doc="忽略'航空测量'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info,doc="获取弹框提示语")
        self.click(PPL.plumbing_sure,doc="航空测量专业忽略弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.communication_do,doc="获取通信专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent,doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent,doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.money_result_finish_pro,doc="获取新能源-收资-成果完成进度")
        text_5 = self.get_element_text(PPL.energy_money_finsh_pro,doc="获取新能源-收资-阶段完成进度")
        text_6 = self.get_element_text(PPL.energy_finsh_pro,doc="获取新能源-业务模块完成进度")
        text_7 = self.get_element_text(PPL.project_proc_new,doc="项目状态完成进度")
        text_8 = self.get_element_text(PPL.communication_process_percent,doc="获取通信专业专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.communication_finish_percent,doc="获取通信专业专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.aerial_survey_process_percent,doc="获取航空测量专业进度'进度占比'")
        text_11 = self.get_element_text(PPL.aerial_survey_finish_percent,doc="获取航空测量专业进度'完成进度'")
        text_12 = self.get_element_text(PPL.resources_process_percent,doc="获取资源专业进度'进度占比'")
        text_13 = self.get_element_text(PPL.general_layout_process_percent,doc="获取总图专业进度'进度占比'")
        text_14 = self.get_element_text(PPL.ground_process_percent,doc="获取场区电气一次专业进度'进度占比'")
        text_15 = self.get_element_text(PPL.ground_two_process_percent,doc="获取场区电气二次专业进度'进度占比'")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(1)
        text_16 = self.get_element_text(PPL.process_percent,doc="获取列表页进度百分比")
        return text_0,text_1,text_2,text_3,text_4,text_5,text_6,text_7,text_8,text_9,text_10,text_11,text_12,text_13,text_14,text_15,text_16

    def resources_finsh(self):
        self.click(PPL.process_percent,doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box,doc="勾选'显示进度占比'框")
        self.click(PPL.resources_finish,doc="完成'资源'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info,doc="获取弹框提示语")
        self.click(PPL.plumbing_sure,doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent,doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent,doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent,doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent,doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent,doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent,doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro,doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro,doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro,doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new,doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc,doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc,doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent,doc="获取列表页进度百分比")
        return text_0,text_1,text_2,text_3,text_4,text_5,text_6,text_7,text_8,text_9,text_10,text_11,\
               text_12,text_13,text_14,text_15,text_16,text_17,text_18,text_19,text_20,text_21,text_22,text_23,text_24,text_25,text_26

    def general_layout_finsh(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.general_layout_finish, doc="完成'总图'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26


    def ground_ignore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.ground_ignore, doc="忽略'场区电气'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def ground_two_ignore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.ground_two_ignore, doc="忽略'场区电气二次'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(4)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(4)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26


    def communication_restore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.communication_restore, doc="恢复'通信'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def aerial_survey_restore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.aerial_survey_restore, doc="恢复'航空测量'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def resource_fallback(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.resources_fallback, doc="回退'资源'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def ground_restore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(10)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.ground_restore, doc="恢复'场区电气一次次'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def ground_two_restore(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.ground_two_restore, doc="恢复'场区电气二次'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def plumbing_fallback(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.plumbing_fallback, doc="回退'水暖'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26

    def general_layout_fallback(self):
        self.click(PPL.process_percent, doc="列表页点击进度百分比")
        sleep(6)
        self.click_by_js(PPL.show_process_box, doc="勾选'显示进度占比'框")
        self.click(PPL.general_layout_fallback, doc="回退'总图'专业")
        text_0 = self.get_element_text(PPL.plumbing_box_info, doc="获取弹框提示语")
        self.click(PPL.plumbing_sure, doc="资源专业完成弹框点'确定'")
        sleep(2)
        text_1 = self.get_element_text(PPL.plumbing_do, doc="获取水暖专业操作列")
        text_2 = self.get_element_text(PPL.plumbing_process_percent, doc="获取水暖专业进度占比")
        text_3 = self.get_element_text(PPL.plumbing_finish_percent, doc="获取水暖专业完成进度")
        text_4 = self.get_element_text(PPL.communication_do, doc="获取通信专业操作列")
        text_5 = self.get_element_text(PPL.communication_process_percent, doc="获取通信专业专业进度'进度占比'")
        text_6 = self.get_element_text(PPL.communication_finish_percent, doc="获取通信专业专业进度'完成进度'")
        text_7 = self.get_element_text(PPL.aerial_survey_do, doc="获取航空测量操作列")
        text_8 = self.get_element_text(PPL.aerial_survey_process_percent, doc="获取航空测量专业进度'进度占比'")
        text_9 = self.get_element_text(PPL.aerial_survey_finish_percent, doc="获取航空测量专业进度'完成进度'")
        text_10 = self.get_element_text(PPL.resources_do, doc="获取资源专业操作列")
        text_11 = self.get_element_text(PPL.resources_process_percent, doc="获取资源专业'进度占比'")
        text_12 = self.get_element_text(PPL.resources_finish_percent, doc="获取资源专业'完成进度'")
        text_13 = self.get_element_text(PPL.general_layout_do, doc="获取总图专业操作列")
        text_14 = self.get_element_text(PPL.general_layout_process_percent, doc="获取资源专业'进度占比'")
        text_15 = self.get_element_text(PPL.general_layout_finish_percent, doc="获取资源专业'完成进度'")
        text_16 = self.get_element_text(PPL.ground_do, doc="获取场区电气一次专业操作列")
        text_17 = self.get_element_text(PPL.ground_process_percent, doc="获取场区电气一次专业'进度占比'")
        text_18 = self.get_element_text(PPL.ground_finish_percent, doc="获取场区电气一次专业'完成进度'")
        text_19 = self.get_element_text(PPL.ground_two_do, doc="获取场区电气二次专业操作列")
        text_20 = self.get_element_text(PPL.ground_two_process_percent, doc="获取场区电气二次专业'进度占比'")
        text_21 = self.get_element_text(PPL.ground_two_finish_percent, doc="获取场区电气二次专业'完成进度'")
        text_22 = self.get_element_text(PPL.money_result_finish_pro, doc="获取新能源-收资-成果完成进度")
        text_23 = self.get_element_text(PPL.energy_money_finsh_pro, doc="获取新能源-收资-阶段完成进度")
        text_24 = self.get_element_text(PPL.energy_finsh_pro, doc="获取新能源-业务模块完成进度")
        text_25 = self.get_element_text(PPL.project_proc_new, doc="项目状态完成进度")
        self.driver.refresh()
        self.click(PPL.projectmanager_loc, doc="首页_点击'项目管理'")
        self.click(PPL.projectplatform_loc, doc="首页_点击'项目台账'")
        sleep(1)
        text_26 = self.get_element_text(PPL.process_percent, doc="获取列表页进度百分比")
        return text_0, text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, \
               text_12, text_13, text_14, text_15, text_16, text_17, text_18, text_19, text_20, text_21, text_22, text_23, text_24, text_25, text_26






